# Generated by Django 4.2.27 on 2026-02-02 04:46

import cv.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres completos')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Cédula/Identificación')),
                ('fecha_nacimiento', models.DateField(validators=[cv.models.validar_fecha_nacimiento], verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(default='Ecuatoriana', max_length=100, verbose_name='Nacionalidad')),
                ('lugar_nacimiento', models.CharField(max_length=200, verbose_name='Lugar de nacimiento')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero/a'), ('Casado', 'Casado/a'), ('Divorciado', 'Divorciado/a'), ('Viudo', 'Viudo/a'), ('Union Libre', 'Unión Libre')], max_length=20, verbose_name='Estado civil')),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono fijo')),
                ('telefono_movil', models.CharField(blank=True, max_length=20, verbose_name='Teléfono móvil')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('licencia_conducir', models.BooleanField(default=False, verbose_name='Tiene licencia de conducir')),
                ('tipo_licencia', models.CharField(blank=True, max_length=10, verbose_name='Tipo de licencia')),
                ('sobre_mi', models.TextField(help_text='Breve descripción profesional', verbose_name='Sobre mí')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto de perfil')),
                ('mostrar_experiencia', models.BooleanField(default=True, verbose_name='Mostrar experiencia laboral')),
                ('mostrar_cursos', models.BooleanField(default=True, verbose_name='Mostrar cursos realizados')),
                ('mostrar_reconocimientos', models.BooleanField(default=True, verbose_name='Mostrar reconocimientos')),
                ('mostrar_productos_academicos', models.BooleanField(default=True, verbose_name='Mostrar productos académicos')),
                ('mostrar_productos_laborales', models.BooleanField(default=True, verbose_name='Mostrar productos laborales')),
                ('mostrar_venta_garage', models.BooleanField(default=True, verbose_name='Mostrar venta garage')),
                ('activo', models.BooleanField(default=True, verbose_name='Perfil activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-activo', '-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular')], max_length=10, verbose_name='Estado')),
                ('fecha_publicacion', models.DateField(validators=[cv.models.validar_fecha_no_futura], verbose_name='Fecha de publicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='garage/', verbose_name='Imagen del producto')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='cv.perfil')),
            ],
            options={
                'verbose_name': 'Artículo Venta Garage',
                'verbose_name_plural': 'Venta Garage',
                'ordering': ['-fecha_publicacion', '-disponible'],
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título del reconocimiento')),
                ('tipo', models.CharField(help_text='Ej: Premio, Certificado, Mención honorífica', max_length=200, verbose_name='Tipo')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución que otorga')),
                ('fecha', models.DateField(validators=[cv.models.validar_fecha_no_futura], verbose_name='Fecha del reconocimiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado (PDF/Imagen)')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cv.perfil')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(validators=[cv.models.validar_fecha_no_futura], verbose_name='Fecha de creación/entrega')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa/Cliente')),
                ('tecnologias', models.CharField(blank=True, max_length=500, verbose_name='Tecnologías utilizadas')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='productos/', verbose_name='Archivo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='cv.perfil')),
            ],
            options={
                'verbose_name': 'Producto Laboral',
                'verbose_name_plural': 'Productos Laborales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(validators=[cv.models.validar_fecha_no_futura], verbose_name='Fecha de publicación/creación')),
                ('clasificador', models.CharField(help_text='Ej: ingeniería,tecnologiasinformacion,basesdedatos,pregrado,docencia', max_length=500, verbose_name='Clasificador (etiquetas separadas por comas)')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='productos/', verbose_name='Archivo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.perfil')),
            ],
            options={
                'verbose_name': 'Producto Académico',
                'verbose_name_plural': 'Productos Académicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo/Puesto')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa/Institución')),
                ('fecha_inicio', models.DateField(validators=[cv.models.validar_fecha_minima_2000], verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura], verbose_name='Fecha de fin')),
                ('actualmente_trabajando', models.BooleanField(default=False, verbose_name='Actualmente trabajando aquí')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de funciones')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado (PDF/Imagen)')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.perfil')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=300, verbose_name='Nombre del curso')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución')),
                ('fecha_inicio', models.DateField(validators=[cv.models.validar_fecha_minima_2000], verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(validators=[cv.models.validar_fecha_no_futura], verbose_name='Fecha de finalización')),
                ('duracion_horas', models.IntegerField(blank=True, null=True, verbose_name='Duración (horas)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado (PDF/Imagen)')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cv.perfil')),
            ],
            options={
                'verbose_name': 'Curso Realizado',
                'verbose_name_plural': 'Cursos Realizados',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
