# Generated by Django 6.0.1 on 2026-02-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='mostrar_venta_garage',
        ),
        migrations.DeleteModel(
            name='VentaGarage',
        ),
    ]
