# Generated by Django 6.0.1 on 2026-02-02 16:31

import cv.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_perfil_mostrar_venta_garage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='mostrar_venta_garage',
            field=models.BooleanField(default=True, verbose_name='Mostrar venta garage'),
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular')], max_length=10, verbose_name='Estado')),
                ('fecha_publicacion', models.DateField(validators=[cv.models.validar_fecha_no_futura], verbose_name='Fecha de publicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='garage/', verbose_name='Imagen del producto')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='cv.perfil')),
            ],
            options={
                'verbose_name': 'Artículo Venta Garage',
                'verbose_name_plural': 'Venta Garage',
                'ordering': ['-fecha_publicacion', '-disponible'],
            },
        ),
    ]
