# Generated by Django 6.0.1 on 2026-02-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_perfil_mostrar_venta_garage_ventagarage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconocimiento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='email_empresa_patrocinadora',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Email empresa patrocinadora'),
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='nombre_contacto_auspicia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de contacto que auspicia'),
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='telefono_contacto_auspicia',
            field=models.CharField(blank=True, max_length=60, verbose_name='Teléfono de contacto que auspicia'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email de la empresa'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='lugar_empresa',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lugar de la empresa'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombre_contacto_empresarial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de contacto empresarial'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='sitio_web_empresa',
            field=models.URLField(blank=True, max_length=100, verbose_name='Sitio web de la empresa'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='telefono_contacto_empresarial',
            field=models.CharField(blank=True, max_length=60, verbose_name='Teléfono de contacto empresarial'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección de trabajo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sitio_web',
            field=models.URLField(blank=True, max_length=60, verbose_name='Sitio web personal'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono_convencional',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono convencional'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='nombre_contacto_auspicia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de contacto que auspicia'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='telefono_contacto_auspicia',
            field=models.CharField(blank=True, max_length=60, verbose_name='Teléfono de contacto que auspicia'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='tipo_reconocimiento',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], default=1, max_length=20, verbose_name='Tipo de reconocimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='institucion',
            field=models.CharField(max_length=200, verbose_name='Institución patrocinadora'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección domiciliaria'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='institucion',
            field=models.CharField(max_length=200, verbose_name='Entidad patrocinadora'),
        ),
    ]
