# Generated by Django 6.0.1 on 2026-02-03 02:25

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_reconocimiento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='duracion_horas',
            field=models.IntegerField(blank=True, null=True, validators=[cv.models.validar_horas_positivas], verbose_name='Duración (horas)'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='telefono_contacto_auspicia',
            field=models.CharField(blank=True, max_length=60, validators=[cv.models.validar_telefono], verbose_name='Teléfono de contacto que auspicia'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefono_contacto_empresarial',
            field=models.CharField(blank=True, max_length=60, validators=[cv.models.validar_telefono], verbose_name='Teléfono de contacto empresarial'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_convencional',
            field=models.CharField(blank=True, max_length=15, validators=[cv.models.validar_telefono], verbose_name='Teléfono convencional'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=15, validators=[cv.models.validar_telefono], verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=20, validators=[cv.models.validar_telefono], verbose_name='Teléfono móvil'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='telefono_contacto_auspicia',
            field=models.CharField(blank=True, max_length=60, validators=[cv.models.validar_telefono], verbose_name='Teléfono de contacto que auspicia'),
        ),
    ]
